name: Testing and packaging for post releases
on:
  push:
    branches:
      - v*.*.*-post*
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.editorconfig'
      - 'scripts/**'
      - '.github//**'
      - '!.github/workflows/on_push.yml'
      - '!.github/workflows/coverage.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  extract_duckdb_tag:
    runs-on: ubuntu-24.04
    outputs:
      duckdb_version: ${{ steps.extract_version.outputs.version }}
    steps:
      - name: Get DuckDB version from branch name
        id: extract_version
        shell: bash
        run: |
          BRANCH="${{ github.ref_name }}"
          VERSION="${BRANCH%%-*}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  packaging_test:
    name: Build and test post release packages and upload to S3
    needs: extract_duckdb_tag
    uses: ./.github/workflows/packaging.yml
    with:
      minimal: false
      testsuite: all
      git-ref: ${{ github.ref }}
      duckdb-git-ref: ${{ needs.extract_duckdb_tag.outputs.duckdb_version }}
      force-version: ${{ github.ref_name }}
